### ISSUE TITLE
Invalid Argument error

### ISSUE THREAD

**Issue by cboto314** [dievus/msdorkdump#1]
I got this error which stopped the program.

> Traceback (most recent call last):
>   File "C:\Users\catarina\msdorkdump\msdorkdump.py", line 89, in <module>
>     msdorker()
>   File "C:\Users\catarina\msdorkdump\msdorkdump.py", line 61, in msdorker
>     urllib.request.urlretrieve(url_path, f'{tail}')
>   File "C:\Python310\lib\urllib\request.py", line 251, in urlretrieve
>     tfp = open(filename, 'wb')
> OSError: [Errno 22] Invalid argument: 'index.php?option=com_docman&task=doc_download&gid=1541&lang=pt'

I ran it with this command 
python msdorkdump.py ualg.pt

Could you check? Thanks.

**Comment by dievus** [comment]
Hi there. Are you trying to open it with python3?  I can't reproduce the error.
